name: Get Size

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: size-limit-action
        uses: andresz1/size-limit-action@v1.7.0
